= git status

Отображает информацию о состоянии индекса, рабочей директории и комммита

Один и тот же файл может одновременно отображаться и как индексированный (в stage), и как неиндексированный. Если он был проиндексирован, а затем изменен. Если проиндексировать его еще раз, он попадет в stqged и пропадет из списка непроиндексированных файлов.

*_git status –short_* - сокращенный вывод статуса.

[cols=2]

|===
|*$*
|git status -s

|*M* 
|README

|*MM* 
|Rakefile

|*A* 
|lib/git.rb

|*M* 
|lib/simplegit.rb

|*??*
|LICENSE.txt

|===
--

. Новые неотслеживаемые файлы помечены ?? слева от них
. Файлы добавленные в отслеживаемые помечены A
. Отредактированные файлы помечены M
. В выводе содержится два столбца — в левом указывается статус файла, а в правом модифицирован ли он после этого (Например, MM)

*Файлы выше:*

. Файл README модифицирован в рабочем каталоге, но не проиндексирован
. Файл lib/simplegit.rb модифицирован и проиндексирован. 3. Файл Rakefile модифицирован, проиндексирован и ещё раз модифицирован, то есть, в нем есть часть, которая попадет в коммит, и которая не.
