= gitignore

В *gitignore* указываются файлы, которые *НЕ* попадают в коммит ни при каких условиях. Обычно это автоматически генерируемые файлы (различные логи, результаты сборки программ и т. п.) Внутри *gitignore* используются регулярки для создания множества имен файлов, которые надо проигнорировать при помещении в коммит.

.	Пустые строки, а также строки, начинающиеся с #, игнорируются.
.	Стандартные шаблоны являются глобальными и применяются рекурсивно для всего дерева каталогов.
.	Чтобы избежать рекурсии используйте символ слеш (/) в начале шаблона.
.	Чтобы исключить каталог добавьте слеш (/) в конец шаблона.
.	Можно инвертировать шаблон, использовав восклицательный знак (!) в качестве первого символа.

Примеры:

[cols=2]

|===

| *.a
| # Исключить все файлы с расширением .a

| !lib.a
| # Но отслеживать файл lib.a даже если он подпадает под исключение выше

| /TODO
| # Исключить файл TODO в корневом каталоге, но не файл в subdir/TODO

| build/
| # Игнорировать все файлы в каталоге build/

| doc/*.txt
| # Игнорировать файл doc/notes.txt, но не файл doc/server/arch.txt

| doc/**/*.txt
| # Игнорировать все .txt файлы в каталоге doc/

|===

gitignore-файл может содержаться не только в главной папке, но и в под-папках. Тогда он применяется лишь для своего уровня.
